version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master